### ISSUE TITLE
Demo has to be on https://

### ISSUE THREAD

**Issue by KasperAndersson** [kdzwinel/JS-face-tracking-demo#2]
`"getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details."`

**Comment by kdzwinel** [comment]
Thanks for reporting. Github pages offer https, so it's just a matter of modifying a link. I totally forgot about it because I'm using "HTTPS everywhere" so I never experienced any issues. Anyway, I've updated URLs in the project description and readme. Maybe I'll consider JS redirect later on.

**Comment by KasperAndersson** [comment]
Ah great, wasn't aware of that. Thanks a lot.
