### ISSUE TITLE
How to recording video?

### ISSUE THREAD

**Issue by joeattia2008** [kdzwinel/JS-face-tracking-demo#3]

**Comment by kdzwinel** [comment]
Click the big green "record" button. Make sure you allow camera access!

**Comment by joeattia2008** [comment]
What I meant that how to record video with audio to make mp4 not gif img?

**Comment by kdzwinel** [comment]
Hm, sorry I'm not sure. Haven't done it in a while, but here is the record function that you'll have to modify to produce mp4 instead of gif: https://github.com/kdzwinel/JS-face-tracking-demo/blob/gh-pages/js/main.js#L200

**Comment by joeattia2008** [comment]
Thank you , I will try to modify the file.
